[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rustfund = "6vxyM2QFNg3njwCQksy4K8azF5NwKxiUkEEG2hxqz15h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
